export const PKG_PREFIX = '@p-helper'
export const PKG_NAME = 'p-helper'
export const PKG_CAMELCASE_NAME = 'PHelper'
export const PKG_CAMELCASE_LOCAL_NAME = 'PHelperLocale'
export const PKG_BRAND_NAME = 'P Helper'
