
name: 更新npm

on:
  release:
    types: [created]

#  push:
#    branches: ['dev-publish-com']
jobs:
  publish:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 18.20.3 ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.com/

      - name: Get version
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get git head
        run: echo "GIT_HEAD=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Gen npmrc
        run: echo "//registry.npmjs.com/:_authToken=${{ secrets.P_HELPER_PUBLISH }}" >> ./.npmrc

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Get GIT_OWNER
        run: echo "GIT_OWNER=${{github.repository_owner}}" >> $GITHUB_ENV

      - name: Get GIT_REPOSITORY
        run: echo "GIT_REPOSITORY=${{github.repository_owner}}"

      - name: ttt
        run: pnpm -v

      - name: nnn
        run: node -v

      - name: Build&publish
        run: sh ./scripts/publish.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.P_HELPER_PUBLISH}}
          TAG_VERSION: ${{env.TAG_VERSION}}
          GIT_HEAD: ${{env.GIT_HEAD}}
          REGISTRY: https://registry.npmjs.com/
          FORCE_COLOR: 2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=4096
